// Copyright (c) 2015 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(p){var d,b={_breaker:{},_start:null,each:function(){var a;return function(c,e,f){var h,d;d=b.type(c);var k=new Date;if(1===arguments.length)a=arguments[0];else if(f=b.extend({timeout:!1},f),"object"===d&&c.hasOwnProperty)for(h in c){if(c.hasOwnProperty(h)&&(e(c[h],h)===b._breaker||f.timeout&&b.elapsed(k)>a))break}else if(c){h=0;for(d=c.length;h<d&&!(e(c[h],h)===b._breaker||f.timeout&&b.elapsed(k)>a);h++);}}}(),extend:function(a){var c,e,b,h,d=arguments.length;a=a||{};for(e=1;e<d;e++)if(h=
arguments[e],void 0!==h&&null!==h)for(b in h)c=h[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(a,e){try{return("function"===typeof window[e]||"object"===typeof window[e])&&a instanceof window[e]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||
"parentWindow"in c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},all:function(a,c){var e="array"===b.type(a)?[]:{};b.each(a,function(a,h){c(a,h)&&("array"===b.type(e)?e.push(a):e[h]=a)});return e},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},attrValues:function(a,c,b){return(c=a[c])&&c.split?c.split(b||" "):[]},batchable:function(a,
c){c=c||b.noop;var e=function(){return b.extend({batch:!0,timeout:100},c())},f=b.traits.cors&&b.traits.json,h=[],d=null,k=function(){null!==d&&(clearTimeout(d),d=null);1===h.length?a.apply(null,h[0].arguments):1<h.length&&a.apply(null,h);h=[]},q=function(){h.push({arguments:b.toArray(arguments),batch:!0});!f||!e().batch?k():null===d&&(d=setTimeout(b.entryPoint(b.bind(function(){k()},this)),e().timeout))};b.extend(q,{flush:k,now:a});return q},batchArgs:function(a,c){return b.map(a,function(a){return void 0===
c?a.arguments:a.arguments[c]})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(a){return"object"===b.type(a)&&a.batch&&"array"===b.type(a.arguments)}).length===a.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),b=0;return function(f,h,d){if(f){var k=f[c];if(k||void 0!==d)return k||(k=++b),a[k]||(f[c]=k,a[k]={}),void 0!==d&&(a[k][h]=d),"string"===typeof h?a[k][h]:a[k]}}}(),canonicalizeHostname:function(a){"string"===
typeof a&&(a=b.createA(a));try{return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""}catch(c){return""}},clone:function(a){return b.extend({},a)},contains:function(a,c){return Boolean(b.find(a,function(a){return a===c}))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},contextIsAncestor:function(a,c){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,
b===c)return!0;return!1},cors:function(a,c,b){var f,h=function(){b?b(f.responseText):eval(f.responseText)};f=new window.XMLHttpRequest;f.onreadystatechange=function(){4===f.readyState&&200===f.status&&h()};try{return f.open("POST",a),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.withCredentials=!0,f.send(c),!0}catch(d){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,e,f){var h;a=(f||document).createElement(a);c=c||{};e=e||
{};for(h in c)void 0!==c[h]&&(a[h]=c[h]);b.css(a,e);return a},css:function(a,c){for(var b in c)try{a.style[b]=c[b]}catch(f){}return a},destructing:function(a){return function(a){var b=!1,f;return function(){b||(f=a.apply(null,arguments),b=!0);return f}}(a)},elapsed:function(a){return(a=a||this._start)?(new Date).getTime()-a.getTime():0},entryPoint:function(a){return b.exceptionLogger(function(){var c;b._start=new Date;b.observer.pause();c=a.apply(this,arguments);b.observer.resume();return c})},escapeRegExp:function(){var a;
return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(f){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,f){if(void 0!==f)a=f,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(f){c(f)}else return b.apply(this,arguments)}}}(),find:function(a,c,e){var f;b.each(a,
function(a,e){if(c(a,e))return f=a,b._breaker},e);return f},generateNodeFilter:function(){var a=function(a,b){var h,d;b=","+b.join(",")+",";h=0;for(d=a.length;h<d;h++)if(c(a[h],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(e){e=b.extend({custom:null,classes:[],rels:[],tags:[]},e);e.tags.length&&(e.tags=","+e.tags.join(",").toLowerCase()+",");return function(f,h){h=b.extend({ancestors:!0,self:!0},h);var d=function(f,h){var d;if(d=!(e.tags.length&&c(f.nodeName.toLowerCase(),
e.tags))){if(d=e.classes.length){d=e.classes;var t=b.attrValues(f,"className");d=a(d,t)}if(d=!d){if(d=e.rels.length)d=e.rels,t=b.attrValues(f,"rel"),d=c(f.nodeName.toLowerCase(),",a,")&&a(d,t);d=!d&&!("function"===b.type(e.custom)&&e.custom(f,h))}}return d};if(h.self&&!d(f,!0))return!1;if(h.ancestors)for(;f.parentNode;)if(f=f.parentNode,1===f.nodeType&&!d(f,!1))return!1;return!0}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},fromQuery:function(a){"?"===a.substr(0,
1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,e=Infinity,f=Infinity,h=-Infinity,d=-Infinity,k;for(a=0;a<c;a++)k=b.position(arguments[a]),e=Math.min(e,k.x),f=Math.min(f,k.y),h=Math.max(h,k.x+arguments[a].offsetWidth),d=Math.max(d,k.y+arguments[a].offsetHeight);return{x:e,y:f,w:h-e,h:d-f,x1:e,y1:f,x2:h,y2:d}},getActualHref:function(a){return b.cache(a,"href")||
a.href},hasAttrValue:function(a,c,e,f){return c?b.contains(b.attrValues(a,c,f),e):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&a.offsetParent)},jsonp:function(a){var c=document.getElementsByTagName("script")[0];
a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c,e){return b.reduce([],a,function(a,b,e){a.push(c(b,e));return a},e)},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(e){return!0}},nodesOfType:function(a){var c=b.toArray(arguments).slice(1);return b.all(a,function(a){return b.contains(c,a.nodeType)})},on:function(){var a;return function(c,e,f){var h,d,k;if(1===arguments.length)a=c;else{if(2===
arguments.length){if(!a)return;f=e;e=c;c=a}else h=b.toArray(arguments).slice(3,arguments.length);try{d=c["on"+e]}catch(q){}"function"===typeof d&&(c["on"+e]=b.bind(function(a){a=a||window.event;var e=d.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==e&&!1!==a.returnValue&&(a.returnValue=e),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):e})()},this));k=b.entryPoint(function(){if(a.enabled())return f.apply(null,b.toArray(arguments).concat(h||
[]))});c.addEventListener?c.addEventListener(e,k,!1):c.attachEvent&&c.attachEvent("on"+e,k)}}}(),position:function(a,c){var e,f=0,h=0,d=0,k=0;c=c||document;if(!b.isInDom(a))return!1;e=a;do f+=e.offsetLeft,h+=e.offsetTop,e=e.offsetParent;while(e);e=a;do d+=e.scrollLeft,k+=e.scrollTop,e=e.parentNode;while(e&&e!==c.body);return{x:f-d,y:h-k}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(c,b){(null===c||void 0===c)&&delete a[b]});
return a},ready:function(){var a=!1,c=[],e=!1,f,h,d,k,q;document.addEventListener?d=function(){document.removeEventListener("DOMContentLoaded",d,!1);q()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),q())});f=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return q();if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",
k);var c=!1;try{c=null===window.frameElement}catch(e){}document.documentElement.doScroll&&c&&h()}b.on(window,"load",q)}};h=function(){if(!e){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.entryPoint(h),1);return}q()}};q=function(){if(!e){if(!document.body)return setTimeout(b.entryPoint(q),13);e=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){f();e?a():c.push(a)}}(),reduce:function(a,c,e,f){b.each(c,function(c,b){a=e(a,c,b)},f);return a},reformatKeys:function(a){var c,
e,f=function(a){return"_"+a.toLowerCase()};for(c in a)e=c.replace(/([A-Z])/g,f),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),e!==c&&(a[e]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var e,f,h=b.attrValues(a,"className");e=0;for(f=h.length;e<f;e++)h[e]===c&&delete h[e];a.className=h.join(" ")}},request:function(a,c,e){var f,h,d,k=b.uniqid("vglnk_"),q=b.toArray(arguments).slice(3,arguments.length),g=function(a,c,e){var f=b.createA(a).protocol;c.length&&(a=b.updateUrl(a,
{search:"?"+c}));if(!0===e||!1===e)a=b.updateUrl(a,{protocol:f.replace(/s?:$/,function(){return e?"s:":":"})});return a};e=b.extend({fn:b.noop,jsonp:!0,"return":!1,ssl:null,timeout:null},e);"string"===typeof e.fn?(f=window[e.fn],k=e.fn):"function"===typeof e.fn&&(f=e.fn);"function"===b.type(f)&&(d=b.entryPoint(b.destructing(function(){f.apply(this,b.toArray(arguments).concat(q));window[k]&&(window[k]=void 0)})),null!==e.timeout&&setTimeout(d,e.timeout));!0===e.jsonp&&(window[k]=d,c=b.extend({format:"jsonp",
jsonp:k},c));h=b.toQuery(c);return e["return"]?g(a,h,e.ssl):b.traits.cors&&b.cors(g(a,"",e.ssl),h,e.jsonp?null:d)?!0:b.jsonp(g(a,h,e.ssl))},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},stopPropagation:function(a){a&&a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(c){var b,f,d=[];b=0;for(f=a.length;b<f;b++)d[b]=a[b];return d}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},
toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}(),unique:function(a){return b.reduce([],a,function(a,e){b.contains(a,e)||a.push(e);return a})},unlink:function(a){var c,b=document.createDocumentFragment();if(a.parentNode){for(;null!==(c=a.firstChild);)b.appendChild(c);
a.parentNode.insertBefore(b,a);a.parentNode.removeChild(a)}},withScope:function(){var a=function(a,e,f){if(f.self&&b.contains(e,a))return a;if(f.ancestors)return b.find(b.ancestors(a).slice(0),function(a){return b.contains(e,a)},{timeout:!0})};return function(c,e,f){var d=b.select(e);f=b.extend({ancestors:!0,consolidate:!1,descendants:!0,self:!0},f);c=b.all(b.map(c,function(c){var e,q=[];(e=a(c,d,f))?q.push(e):1===c.nodeType&&f.descendants&&b.each(d,function(a){b.contains(b.ancestors(a),c)&&q.push(a)},
{timeout:!0});return[c,q]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0});return f.consolidate?b.reduce([],c,function(a,c){return a.concat(c[1])}):c}}()});var u=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};u.amd=!0;(function(a){function c(a,c,b,e){var f,d,h,k,g;(c?c.ownerDocument||c:B)!==z&&I(c);c=c||z;b=b||[];if(!a||"string"!==typeof a)return b;if(1!==(k=c.nodeType)&&9!==k)return[];if(E&&!e){if(f=sa.exec(a))if(h=f[1])if(9===
k)if((d=c.getElementById(h))&&d.parentNode){if(d.id===h)return b.push(d),b}else return b;else{if(c.ownerDocument&&(d=c.ownerDocument.getElementById(h))&&S(c,d)&&d.id===h)return b.push(d),b}else{if(f[2])return J.apply(b,c.getElementsByTagName(a)),b;if((h=f[3])&&v.getElementsByClassName&&c.getElementsByClassName)return J.apply(b,c.getElementsByClassName(h)),b}if(v.qsa&&(!A||!A.test(a))){d=f=x;h=c;g=9===k&&a;if(1===k&&"object"!==c.nodeName.toLowerCase()){k=T(a);(f=c.getAttribute("id"))?d=f.replace(ta,
"\\$&"):c.setAttribute("id",d);d="[id='"+d+"'] ";for(h=k.length;h--;)k[h]=d+r(k[h]);h=da.test(a)&&w(c.parentNode)||c;g=k.join(",")}if(g)try{return J.apply(b,h.querySelectorAll(g)),b}catch(q){}finally{f||c.removeAttribute("id")}}}return ja(a.replace(Y,"$1"),c,b,e)}function b(){function a(b,e){c.push(b+" ")>s.cacheLength&&delete a[c.shift()];return a[b+" "]=e}var c=[];return a}function f(a){a[x]=!0;return a}function d(a){var c=z.createElement("div");try{return!!a(c)}catch(b){return!1}finally{c.parentNode&&
c.parentNode.removeChild(c)}}function g(a,c){for(var b=a.split("|"),e=a.length;e--;)s.attrHandle[b[e]]=c}function k(a,c){var b=c&&a,e=b&&1===a.nodeType&&1===c.nodeType&&(~c.sourceIndex||ka)-(~a.sourceIndex||ka);if(e)return e;if(b)for(;b=b.nextSibling;)if(b===c)return-1;return a?1:-1}function q(a){return function(c){return"input"===c.nodeName.toLowerCase()&&c.type===a}}function m(a){return function(c){var b=c.nodeName.toLowerCase();return("input"===b||"button"===b)&&c.type===a}}function l(a){return f(function(c){c=
+c;return f(function(b,e){for(var f,d=a([],b.length,c),h=d.length;h--;)if(b[f=d[h]])b[f]=!(e[f]=b[f])})})}function w(a){return a&&typeof a.getElementsByTagName!==O&&a}function n(){}function r(a){for(var c=0,b=a.length,e="";c<b;c++)e+=a[c].value;return e}function p(a,c,b){var e=c.dir,f=b&&"parentNode"===e,d=ua++;return c.first?function(c,b,d){for(;c=c[e];)if(1===c.nodeType||f)return a(c,b,d)}:function(c,b,h){var X,ca,k=[C,d];if(h)for(;c=c[e];){if((1===c.nodeType||f)&&a(c,b,h))return!0}else for(;c=
c[e];)if(1===c.nodeType||f){ca=c[x]||(c[x]={});if((X=ca[e])&&X[0]===C&&X[1]===d)return k[2]=X[2];ca[e]=k;if(k[2]=a(c,b,h))return!0}}}function ea(a){return 1<a.length?function(c,b,e){for(var f=a.length;f--;)if(!a[f](c,b,e))return!1;return!0}:a[0]}function P(a,c,b,e,f){for(var d,h=[],k=0,g=a.length,q=null!=c;k<g;k++)if(d=a[k])if(!b||b(d,e,f))h.push(d),q&&c.push(k);return h}function U(a,b,e,d,h,k){d&&!d[x]&&(d=U(d));h&&!h[x]&&(h=U(h,k));return f(function(f,k,g,q){var m,t,l=[],y=[],D=k.length,w;if(!(w=
f)){w=b||"*";for(var n=g.nodeType?[g]:g,r=[],p=0,ra=n.length;p<ra;p++)c(w,n[p],r);w=r}w=a&&(f||!b)?P(w,l,a,g,q):w;n=e?h||(f?a:D||d)?[]:k:w;e&&e(w,n,g,q);if(d){m=P(n,y);d(m,[],g,q);for(g=m.length;g--;)if(t=m[g])n[y[g]]=!(w[y[g]]=t)}if(f){if(h||a){if(h){m=[];for(g=n.length;g--;)if(t=n[g])m.push(w[g]=t);h(null,n=[],m,q)}for(g=n.length;g--;)if((t=n[g])&&-1<(m=h?M.call(f,t):l[g]))f[m]=!(k[m]=t)}}else n=P(n===k?n.splice(D,n.length):n),h?h(null,k,n,q):J.apply(k,n)})}function fa(a){var c,b,e,f=a.length,d=
s.relative[a[0].type];b=d||s.relative[" "];for(var h=d?1:0,k=p(function(a){return a===c},b,!0),g=p(function(a){return-1<M.call(c,a)},b,!0),q=[function(a,b,e){return!d&&(e||b!==Z)||((c=b).nodeType?k(a,b,e):g(a,b,e))}];h<f;h++)if(b=s.relative[a[h].type])q=[p(ea(q),b)];else{b=s.filter[a[h].type].apply(null,a[h].matches);if(b[x]){for(e=++h;e<f&&!s.relative[a[e].type];e++);return U(1<h&&ea(q),1<h&&r(a.slice(0,h-1).concat({value:" "===a[h-2].type?"*":""})).replace(Y,"$1"),b,h<e&&fa(a.slice(h,e)),e<f&&fa(a=
a.slice(e)),e<f&&r(a))}q.push(b)}return ea(q)}function va(a,b){var e=0<b.length,d=0<a.length,h=function(f,h,k,g,q){var m,t,l,y=0,n="0",w=f&&[],D=[],ia=Z,r=f||d&&s.find.TAG("*",q),p=C+=null==ia?1:Math.random()||0.1,qa=r.length;for(q&&(Z=h!==z&&h);n!==qa&&null!=(m=r[n]);n++){if(d&&m){for(t=0;l=a[t++];)if(l(m,h,k)){g.push(m);break}q&&(C=p)}e&&((m=!l&&m)&&y--,f&&w.push(m))}y+=n;if(e&&n!==y){for(t=0;l=b[t++];)l(w,D,h,k);if(f){if(0<y)for(;n--;)!w[n]&&!D[n]&&(D[n]=wa.call(g));D=P(D)}J.apply(g,D);q&&(!f&&
0<D.length&&1<y+b.length)&&c.uniqueSort(g)}q&&(C=p,Z=ia);return w};return e?f(h):h}var Q,v,s,$,la,T,ga,ja,Z,K,R,I,z,F,E,A,N,aa,S,x="sizzle"+-new Date,B=a.document,C=0,ua=0,ma=b(),na=b(),oa=b(),ha=function(a,c){a===c&&(R=!0);return 0},O="undefined",ka=-2147483648,xa={}.hasOwnProperty,L=[],wa=L.pop,ya=L.push,J=L.push,pa=L.slice,M=L.indexOf||function(a){for(var c=0,b=this.length;c<b;c++)if(this[c]===a)return c;return-1},Y=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,za=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,
Aa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ba=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Ca=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),Da=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,
ba={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Ea=/^(?:input|select|textarea|button)$/i,Fa=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,sa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,da=/[+~]/,ta=/'|\\/g,G=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,H=function(a,c,b){a="0x"+c-65536;return a!==a||b?c:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{J.apply(L=pa.call(B.childNodes),B.childNodes),L[B.childNodes.length].nodeType}catch(Ga){J={apply:L.length?function(a,c){ya.apply(a,pa.call(c))}:function(a,c){for(var b=
a.length,e=0;a[b++]=c[e++];);a.length=b-1}}}v=c.support={};la=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};I=c.setDocument=function(a){var c=a?a.ownerDocument||a:B;a=c.defaultView;if(c===z||9!==c.nodeType||!c.documentElement)return z;z=c;F=c.documentElement;E=!la(c);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){I()},!1):a.attachEvent&&a.attachEvent("onunload",function(){I()}));v.attributes=d(function(a){a.className="i";return!a.getAttribute("className")});
v.getElementsByTagName=d(function(a){a.appendChild(c.createComment(""));return!a.getElementsByTagName("*").length});v.getElementsByClassName=V.test(c.getElementsByClassName)&&d(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});v.getById=d(function(a){F.appendChild(a).id=x;return!c.getElementsByName||!c.getElementsByName(x).length});v.getById?(s.find.ID=function(a,c){if(typeof c.getElementById!==O&&E){var b=
c.getElementById(a);return b&&b.parentNode?[b]:[]}},s.filter.ID=function(a){var c=a.replace(G,H);return function(a){return a.getAttribute("id")===c}}):(delete s.find.ID,s.filter.ID=function(a){var c=a.replace(G,H);return function(a){return(a=typeof a.getAttributeNode!==O&&a.getAttributeNode("id"))&&a.value===c}});s.find.TAG=v.getElementsByTagName?function(a,c){if(typeof c.getElementsByTagName!==O)return c.getElementsByTagName(a)}:function(a,c){var b,e=[],f=0,d=c.getElementsByTagName(a);if("*"===a){for(;b=
d[f++];)1===b.nodeType&&e.push(b);return e}return d};s.find.CLASS=v.getElementsByClassName&&function(a,c){if(typeof c.getElementsByClassName!==O&&E)return c.getElementsByClassName(a)};N=[];A=[];if(v.qsa=V.test(c.querySelectorAll))d(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||A.push(":checked")}),d(function(a){var b=c.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(v.matchesSelector=V.test(aa=F.matches||F.webkitMatchesSelector||F.mozMatchesSelector||F.oMatchesSelector||F.msMatchesSelector))&&
d(function(a){v.disconnectedMatch=aa.call(a,"div");aa.call(a,"[s!='']:x");N.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});A=A.length&&RegExp(A.join("|"));N=N.length&&RegExp(N.join("|"));
S=(a=V.test(F.compareDocumentPosition))||V.test(F.contains)?function(a,c){var b=9===a.nodeType?a.documentElement:a,e=c&&c.parentNode;return a===e||!(!e||!(1===e.nodeType&&(b.contains?b.contains(e):a.compareDocumentPosition&&a.compareDocumentPosition(e)&16)))}:function(a,c){if(c)for(;c=c.parentNode;)if(c===a)return!0;return!1};ha=a?function(a,b){if(a===b)return R=!0,0;var e=!a.compareDocumentPosition-!b.compareDocumentPosition;if(e)return e;e=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):
1;return e&1||!v.sortDetached&&b.compareDocumentPosition(a)===e?a===c||a.ownerDocument===B&&S(B,a)?-1:b===c||b.ownerDocument===B&&S(B,b)?1:K?M.call(K,a)-M.call(K,b):0:e&4?-1:1}:function(a,b){if(a===b)return R=!0,0;var e,f=0;e=a.parentNode;var d=b.parentNode,h=[a],W=[b];if(!e||!d)return a===c?-1:b===c?1:e?-1:d?1:K?M.call(K,a)-M.call(K,b):0;if(e===d)return k(a,b);for(e=a;e=e.parentNode;)h.unshift(e);for(e=b;e=e.parentNode;)W.unshift(e);for(;h[f]===W[f];)f++;return f?k(h[f],W[f]):h[f]===B?-1:W[f]===
B?1:0};return c};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==z&&I(a);b=b.replace(Ba,"='$1']");if(v.matchesSelector&&E&&(!N||!N.test(b))&&(!A||!A.test(b)))try{var e=aa.call(a,b);if(e||v.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(f){}return 0<c(b,z,null,[a]).length};c.contains=function(a,c){(a.ownerDocument||a)!==z&&I(a);return S(a,c)};c.attr=function(a,c){(a.ownerDocument||a)!==z&&I(a);var b=s.attrHandle[c.toLowerCase()],
b=b&&xa.call(s.attrHandle,c.toLowerCase())?b(a,c,!E):void 0;return void 0!==b?b:v.attributes||!E?a.getAttribute(c):(b=a.getAttributeNode(c))&&b.specified?b.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var c,b=[],e=0,f=0;R=!v.detectDuplicates;K=!v.sortStable&&a.slice(0);a.sort(ha);if(R){for(;c=a[f++];)c===a[f]&&(e=b.push(f));for(;e--;)a.splice(b[e],1)}K=null;return a};$=c.getText=function(a){var c,b="",e=0;if(c=a.nodeType)if(1===
c||9===c||11===c){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=$(a)}else{if(3===c||4===c)return a.nodeValue}else for(;c=a[e++];)b+=$(c);return b};s=c.selectors={cacheLength:50,createPseudo:f,match:ba,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(G,H);a[3]=(a[3]||a[4]||a[5]||"").replace(G,H);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var c,b=!a[6]&&a[2];if(ba.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(b&&Ca.test(b)&&(c=T(b,!0))&&(c=b.indexOf(")",b.length-c)-b.length))a[0]=a[0].slice(0,c),a[2]=b.slice(0,c);return a.slice(0,3)}},filter:{TAG:function(a){var c=
a.replace(G,H).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===c}},CLASS:function(a){var c=ma[a+" "];return c||(c=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ma(a,function(a){return c.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==O&&a.getAttribute("class")||"")})},ATTR:function(a,b,e){return function(f){f=c.attr(f,a);if(null==f)return"!="===b;if(!b)return!0;f+="";return"="===b?f===e:"!="===b?
f!==e:"^="===b?e&&0===f.indexOf(e):"*="===b?e&&-1<f.indexOf(e):"$="===b?e&&f.slice(-e.length)===e:"~="===b?-1<(" "+f+" ").indexOf(e):"|="===b?f===e||f.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,c,b,e,f){var d="nth"!==a.slice(0,3),h="last"!==a.slice(-4),k="of-type"===c;return 1===e&&0===f?function(a){return!!a.parentNode}:function(c,b,g){var q,m,t,l,y;b=d!==h?"nextSibling":"previousSibling";var n=c.parentNode,w=k&&c.nodeName.toLowerCase();g=!g&&!k;if(n){if(d){for(;b;){for(m=c;m=m[b];)if(k?m.nodeName.toLowerCase()===
w:1===m.nodeType)return!1;y=b="only"===a&&!y&&"nextSibling"}return!0}y=[h?n.firstChild:n.lastChild];if(h&&g){g=n[x]||(n[x]={});q=g[a]||[];l=q[0]===C&&q[1];t=q[0]===C&&q[2];for(m=l&&n.childNodes[l];m=++l&&m&&m[b]||(t=l=0)||y.pop();)if(1===m.nodeType&&++t&&m===c){g[a]=[C,l,t];break}}else if(g&&(q=(c[x]||(c[x]={}))[a])&&q[0]===C)t=q[1];else for(;m=++l&&m&&m[b]||(t=l=0)||y.pop();)if((k?m.nodeName.toLowerCase()===w:1===m.nodeType)&&++t)if(g&&((m[x]||(m[x]={}))[a]=[C,t]),m===c)break;t-=f;return t===e||
0===t%e&&0<=t/e}}},PSEUDO:function(a,b){var e,d=s.pseudos[a]||s.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return d[x]?d(b):1<d.length?(e=[a,a,"",b],s.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var e,f=d(a,b),h=f.length;h--;)e=M.call(a,f[h]),a[e]=!(c[e]=f[h])}):function(a){return d(a,0,e)}):d}},pseudos:{not:f(function(a){var c=[],b=[],e=ga(a.replace(Y,"$1"));return e[x]?f(function(a,c,b,f){f=e(a,null,f,[]);for(var d=a.length;d--;)if(b=f[d])a[d]=!(c[d]=b)}):
function(a,f,d){c[0]=a;e(c,null,d,b);return!b.pop()}}),has:f(function(a){return function(b){return 0<c(a,b).length}}),contains:f(function(a){a=a.replace(G,H);return function(c){return-1<(c.textContent||c.innerText||$(c)).indexOf(a)}}),lang:f(function(a){Da.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(G,H).toLowerCase();return function(c){var b;do if(b=E?c.lang:c.getAttribute("xml:lang")||c.getAttribute("lang"))return b=b.toLowerCase(),b===a||0===b.indexOf(a+"-");while((c=c.parentNode)&&
1===c.nodeType);return!1}}),target:function(c){var b=a.location&&a.location.hash;return b&&b.slice(1)===c.id},root:function(a){return a===F},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&!!a.checked||"option"===c&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!s.pseudos.empty(a)},header:function(a){return Fa.test(a.nodeName)},input:function(a){return Ea.test(a.nodeName)},button:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&"button"===a.type||"button"===c},text:function(a){var c;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(c=a.getAttribute("type"))||"text"===c.toLowerCase())},first:l(function(){return[0]}),
last:l(function(a,c){return[c-1]}),eq:l(function(a,c,b){return[0>b?b+c:b]}),even:l(function(a,c){for(var b=0;b<c;b+=2)a.push(b);return a}),odd:l(function(a,c){for(var b=1;b<c;b+=2)a.push(b);return a}),lt:l(function(a,c,b){for(c=0>b?b+c:b;0<=--c;)a.push(c);return a}),gt:l(function(a,c,b){for(b=0>b?b+c:b;++b<c;)a.push(b);return a})}};s.pseudos.nth=s.pseudos.eq;for(Q in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})s.pseudos[Q]=q(Q);for(Q in{submit:!0,reset:!0})s.pseudos[Q]=m(Q);n.prototype=s.filters=
s.pseudos;s.setFilters=new n;T=c.tokenize=function(a,b){var e,f,d,h,k,g,q;if(k=na[a+" "])return b?0:k.slice(0);k=a;g=[];for(q=s.preFilter;k;){if(!e||(f=za.exec(k)))f&&(k=k.slice(f[0].length)||k),g.push(d=[]);e=!1;if(f=Aa.exec(k))e=f.shift(),d.push({value:e,type:f[0].replace(Y," ")}),k=k.slice(e.length);for(h in s.filter)if((f=ba[h].exec(k))&&(!q[h]||(f=q[h](f))))e=f.shift(),d.push({value:e,type:h,matches:f}),k=k.slice(e.length);if(!e)break}return b?k.length:k?c.error(a):na(a,g).slice(0)};ga=c.compile=
function(a,c){var b,e=[],f=[],d=oa[a+" "];if(!d){c||(c=T(a));for(b=c.length;b--;)d=fa(c[b]),d[x]?e.push(d):f.push(d);d=oa(a,va(f,e));d.selector=a}return d};ja=c.select=function(a,c,b,e){var f,d,h,k,g="function"===typeof a&&a,q=!e&&T(a=g.selector||a);b=b||[];if(1===q.length){d=q[0]=q[0].slice(0);if(2<d.length&&"ID"===(h=d[0]).type&&v.getById&&9===c.nodeType&&E&&s.relative[d[1].type]){if(c=(s.find.ID(h.matches[0].replace(G,H),c)||[])[0])g&&(c=c.parentNode);else return b;a=a.slice(d.shift().value.length)}for(f=
ba.needsContext.test(a)?0:d.length;f--;){h=d[f];if(s.relative[k=h.type])break;if(k=s.find[k])if(e=k(h.matches[0].replace(G,H),da.test(d[0].type)&&w(c.parentNode)||c)){d.splice(f,1);a=e.length&&r(d);if(!a)return J.apply(b,e),b;break}}}(g||ga(a,q))(e,c,!E,b,da.test(a)&&w(c.parentNode)||c);return b};v.sortStable=x.split("").sort(ha).join("")===x;v.detectDuplicates=!!R;I();v.sortDetached=d(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});d(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,c,b){if(!b)return a.getAttribute(c,"type"===c.toLowerCase()?1:2)});(!v.attributes||!d(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&g("value",function(a,c,b){if(!b&&"input"===a.nodeName.toLowerCase())return a.defaultValue});d(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,c,b){var e;if(!b)return!0===a[c]?c.toLowerCase():(e=a.getAttributeNode(c))&&e.specified?e.value:null});"function"===typeof u&&u.amd?u(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);b.browser=function(){var a,c={},e=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(e,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie||c.trident,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.harmony={PASSIVE:1,UNSAFE_QUIRKSMODE_EVENTS:0.5,COMMERCIAL_LINK_EVENTS:0.1,LINK_EVENTS:-1,AGGRESSIVE:-1};b.harmony.DEFAULT=0;b.pii=function(){var a={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},c={contains:function(a,c){return this.regexp(c).test(a)},
redact:function(a,c){return a.replace(this.regexp(c),"___")},regexp:function(c){c=b.extend({},c);var f=b.map(b.all(a,function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+f.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,c){return this.contains(a+" "+document.referrer,c||{numeric:!1})}};return{contains:b.bind(c.contains,c),redact:b.bind(c.redact,c),transmits:b.bind(c.transmits,c)}}();b.platforms=function(){var a={NONE:{id:"full",scope:"body",spec:{selector:"body"}},
bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{parser:/^number(\d+)$/,parse_el:"span[id^=number]",selector:"a[name^='Post'] ~ table"},scope:".post_inner *[id^='body'],.post_inner .signature"},
vb3:{spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,selector:"article[class*='post-'], div[id^='post-']"}}},
c={getPostId:function(a){var c,d;if(this===b.platforms.NONE)return" ";d=this.spec.parse_el?b.select(this.spec.parse_el,a)[0]:a;b.find(this.spec.attributes||["id"],b.bind(function(a){c=d[a]?d[a].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(a){var c=[];b.each(this.getPosts(a),b.bind(function(a){(a=this.getPostId(a))&&!b.contains(c,a)&&c.push(a)},this));return c.length?c:null},getPosts:function(a){var c=[];!a&&(document&&document.body)&&(a=[document.body]);
a&&this.spec&&(c=b.unique(b.reduce([],b.withScope(a,this.spec.selector),function(a,c){return a.concat(c[1])})));return c}};b.each(a,function(e,f){e.id=e.id||f;b.each(c,function(a,c){e[c]=b.bind(a,e)});a[f]=e});a.DEFAULT_POST_ID=" ";a.findById=function(a){return b.find(b.platforms,function(c){return c.id===a})};return a}();b.observer=function(){var a=[],c=0,e=function(a){c||a.observer.observe(a.context.document,{attributes:!1,characterData:!0,childList:!0,subtree:!0})};return{start:function(c,d){if(c.document&&
b.traits.mutation){var g={context:c,observer:new MutationObserver(b.entryPoint(function(a){var c=[];b.each(a,function(a){var e=[];"characterData"===a.type?a.target&&(e=[a.target]):a.addedNodes&&a.addedNodes.length&&(e=b.toArray(a.addedNodes));e.length&&(c=c.concat(e))});0<c.length&&d(c)}))};a.push(g);e(g)}},pause:function(){c++;b.each(a,function(a){a.observer.disconnect()})},resume:function(){c--;b.each(a,e)}}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&
void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),mutation:window.MutationObserver&&!b.browser.ie,quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var g,l,m,n;d={EVENT_LEVEL_LINK:1,EVENT_LEVEL_TOP:2,PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:b.generateNodeFilter({classes:["norewrite"],
rels:["norewrite"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" ")}),api:function(){var a=function(){var a=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,e){var f=c[e],d;if(f&&f.callback&&a){if("string"===b.type(a)&&(d=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(d[1]);f.callback.apply(window,[a].concat(f.data||[]))}})};return function(e){var k={},g={};b.each(e,function(a){a=c.apply(this,a);var e=a.method;
k[e]=b.prune(a.params);g[e]={callback:a.opts.fn||b.noop,data:a.data}});f({data:g,method:"batch",params:b.extend(d.commonParams(),{batch:window.JSON.stringify(k)}),opts:{jsonp:!1,fn:function(c,b){a(c,b)}}})}}(),c=function(a,c,f){var q=b.toArray(arguments).slice(3,arguments.length),m=a,l=e(f),n;n=b.extend(d.commonParams(a),c);n.subId&&n.key!==g.key&&(n.subId=null);return{data:q,method:m,opts:l,params:n}},e=function(a){a=a||{};"function"===b.type(a.fn)&&(a.fn=function(c){return function(e){var f;"object"===
b.type(e)&&("array"===b.type(e.crawl)&&"object"===b.type(n.crawler)&&"function"===b.type(n.crawler.crawl))&&(f=b.map(e.crawl,function(a){return a+""}),delete e.crawl,n.crawler.crawl(f));return c.apply(a,arguments)}}(a.fn));return a},f=function(a){return b.request.apply(b,[g.api_url+"/"+a.method,a.params,a.opts].concat(a.data))};return b.batchable(function(){return b.batched(arguments)?a.call(this,b.batchArgs(arguments)):f(c.apply(this,arguments))},function(){return{batch:g.batch_calls,timeout:g.batch_call_timeout}})}(),
addEventListener:function(a,c){this.fire(a,c)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var d=a.open("",c);d.focus();return d}},c=function(a){var c=a.previousSibling,h=a.nextSibling,g=["",a.textContent,""],k=function(a,c){for(var b=a,e=b.data;(b=b[c+"Sibling"])&&3===b.nodeType;)e+=b.data;return e},m=function(a,c,b){a=a.replace(/\s+/g," ");c=c.replace(/\s+/g," ");b=b.replace(/\s+/g," ");a=a.replace(/^\s+/,"");
" "===c.substr(0,1)&&(c=c.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===c.substr(c.length-1,1)&&(c=c.substr(0,c.length-1),b=(" "!==b.substr(0,1)?" ":"")+b);b=b.replace(/\s+$/,"");return[a,c,b]};void 0!==g[1]&&(g[0]=c&&3===c.nodeType?k(c,"previous"):"",g[2]=h&&3===h.nodeType?k(h,"next"):"",g=m.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,10).join(" "),a={type:"context",
itype:(b.cache(a,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:b.getActualHref(a),v:2},d.log("info",b.toQuery(a))))};return function(e,f){var d,m,k,q,l=b.context(e)||window;f=e.target||f;f=!f||f===l.name||"_top"===f&&l.top===l||"_parent"===f&&l.parent===l?"_self":f;k=a(l,f);if("_self"!==f&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))q="go";else try{if(void 0===k.document)throw!0;q="jsonp"}catch(n){q="go"}d=b.destructing(b.bind(function(){g.time_click&&
arguments.length&&this.logTime("clk");var a=b.toArray(arguments);a.unshift(e,k,f);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof e?e:b.getActualHref(e));if("string"===typeof e&&(e=b.createA(e,f),!this.processLink(e))||!g.enabled)return d();m=this.clickParams(e,q);this.logTime();g.log_context&&c(e);if("go"===q)this.redirect(this.api.now("click",m,{"return":!0}),l,k,f);else if(k===l)this.api.now("click",m,{fn:d,timeout:g.click_timeout});else{if(b.contextIsAncestor(l,k))return this.redirect(b.getActualHref(e),
l,k,f);d=b.entryPoint(d);setTimeout(function(){d()},g.click_timeout);k.document.open();k.callback=d;k.document.write("<html><head><title>"+b.getActualHref(e)+'</title><script type="text/javascript" src="'+this.api.now("click",m,{fn:"callback","return":!0})+'">\x3c/script></head></html>');k.document.close()}}}(),clickParams:function(a,c){var e=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:g.reaffiliate||null,title:window.document.title,txt:a.innerHTML,
loAsUuid:b.cache(a,"uuid")||null,rewrit:b.cache(a,"rewrit")});128<e.txt.length&&(e.txt=e.txt.replace(/<[^>]+>/g,""),e.txt=128<e.txt.length?e.txt.substr(0,125)+"...":e.txt);return e},commonParams:function(a){var c={drKey:g.key?null:g.dr_key,key:g.key,libId:g.library_id,subId:g.sub_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:g.cuid,loc:location.href,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,c){function b(a,c){0==g||1E3<c?a(0==g&&k):setTimeout(function(){b(a,
2*c)},2*c)}function d(){--g||(k=!m&&l)}var k=!1,g=2,m=!1,l=!1;if("function"==typeof c){a+="?ch=*&rn=*";var n=11*Math.random(),r=new Image;r.onload=d;r.onerror=function(){m=!0;d()};r.src=a.replace(/\*/,1).replace(/\*/,n);r=new Image;r.onload=d;r.onerror=function(){l=!0;d()};r.src=a.replace(/\*/,2).replace(/\*/,n);b(c,250)}}}}catch(c){a={detect:function(a,c){c(!0)}}}return function(c){var f=b.updateUrl(g.asset_url,{pathname:"/images/pixel.gif"});a.detect(f,c)}}(),enabled:function(){if(g.enabled&&m!==
window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))g.enabled=!1;return g.enabled},expose:function(){return function(a,c){if((c=c||this[a])&&!n[a]){var e=n,f;f=c;f="function"===b.type(f)?b.entryPoint(b.bind(f,d)):f;e[a]=f}}}(),fire:function(){var a={};return function(c,e){c=c.toLowerCase();var f=a[c]||{fired:!1,listeners:[]};"function"===typeof e?f.fired?setTimeout(function(){e({type:c})},0):f.listeners.push(e):(f.fired=!0,b.each(f.listeners,function(a){"function"===typeof a&&
a({type:c})}),f.listeners=[]);a[c]=f}}(),handleRightClick:function(a,c){if(g.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.entryPoint(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":b.cache(a,"href")&&(a.href=b.cache(a,"href"))}},harmony:function(a){return g.harmony_level<=a},init:function(){var a=function(){var a=!0===window.document.__v5k;
window.document.__v5k=!0;return!a};return function(){var c=this;l={};if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(e){}b.exceptionLogger(b.bind(c.logException,c),!g.dev);b.each(g.script_timeout);return b.entryPoint(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);n=m[p]=b.noop;this.expose("click");
this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("harmony");this.expose("opt");this.expose("platform");this.expose("registerProcessor",function(){if(0<arguments.length)return d.registerProcessor.apply(d,arguments)});b.extend(n,n===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;
c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.entryPoint(b.destructing(b.bind(function(){a=!0;g.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(c){window.DrivingRevenue=void 0}})},initEvents:function(a){var c=b.traits.windowLevelHandlers?a:a.document,e=function(c){c=c||a.event;if((c=b.eventLink(c))&&!b.cache(c,"evented"))m(d.EVENT_LEVEL_LINK,
c),b.cache(c,"evented",!0)},f=function(a){b.observer.start(a,b.batchable(function(a){b.batched(arguments)&&(a=b.reduce([],b.batchArgs(arguments,0),function(a,c){return a.concat(c)}));a=b.all(b.unique(a),function(a){return Boolean(a.parentNode)&&d.allowed(a)});0<a.length&&(b.each(b.withScope(a,"a[href]",{ancestors:!1}),function(a){d.processLinks(a[1])}),b.each(l,function(c,b){d.runPlugin(b,a)}))},function(){return{batch:g.batch_mutation,timeout:g.batch_mutation_timeout}}))},h=function(a,c){return function(){var e=
[a].concat(b.toArray(arguments));c.apply(d,e)}},m=function(a,c){b.on(c,"click",h(a,d.onClick));b.on(c,"contextmenu",h(a,d.onContextmenu))};if(g.dynamic)b.on("DOMReady",function(){f(a)});b.on(c,"copy",b.bind(d.onCopy,d));b.on(c,"mousedown",e);b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",e)})});(!b.traits.quirksMode||d.harmony(b.harmony.UNSAFE_QUIRKSMODE_EVENTS))&&m(d.EVENT_LEVEL_TOP,c)},initLegacyOptions:function(){var a,c={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",
vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in c)void 0!==window[a]&&(n[c[a]]=window[a],"vglnk_domain"===a&&(n[c[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){g.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(d);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){this.processLinks(b.toArray(a.document.links))},this);void 0===a?
b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(p="vglnk");var a=window,c=p.split("."),b;for(p=c.pop();0<c.length;)b=c.shift(),a[b]=a[b]||{},a=a[b];m=a;n=m[p]=m[p]||{}},initOptions:function(){var a;this.initLegacyOptions();g=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,link_urls:!0,partner:null,platform:b.platforms.NONE.id,sub_id:null,
reaffiliate:!1,commercial:null,harmony_level:b.harmony.DEFAULT,link_target:null,rewrite_any:!0,rewrite_modified:!1,rewrite_original:!0}),g,n,{batch_calls:!0,batch_call_timeout:100,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,dynamic:!0,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},script_timeout:2E3,time_click:!1,time_ping:!1,testing_js:[],plugins:{crawler:{},harmony:{},link_affiliation:{},modified_clicks:{}}});for(a in g)"_plugin"===a.substr(-7)&&
delete g[a]},initPlugins:function(){var a,c=1,e={link_affiliation:"convert",link_optimization:"optimize",page_harmony:"harmony",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},f=["spotlight"],h=["harmony"],m=function(b){return function(b){return function(){delete l[b].opts.mode;c=1;clearTimeout(a);q()}}(b)},k=function(a){var c;b.find(e,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:g.key,link_phrases:!1});a[c].link_urls=g.link_urls;return a},
q=function(){var e={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop,"public":{}},f=function(a,c){a.setup=a.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,e,a.setup(a.opts,b.clone(b),n,k(g.key))),a["public"]&&d.expose(c,a["public"],!1)),a.opts.mode!==d.PLUGIN_MANUAL&&d.runPlugin(c))},k=function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);d.log.apply(this,c)}}},m=function(a){return!Boolean(a._ran)};
a=null;b.each(h,function(a){var c=l[a];c&&!Boolean(c._ran)&&f(c,a)});b.each(b.all(l,m),f);b.find(l,m)&&(a=setTimeout(b.entryPoint(q),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},r=function(){setTimeout(function(){d.api.flush()},100);q();b.on("DOMReady",function(){setTimeout(d.api.flush,0)})};return function(a){a=k(a);b.each(a,b.bind(function(a,c){c=e[c]||c;"object"===typeof a&&!1!==a.enabled&&(l[c]={opts:a},b.contains(f,c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&
this.expose("init_"+c,m(c)))},this));r()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(g.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){g.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&
(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isCommercial:function(a){a=b.canonicalizeHostname(a);return"object"===b.type(g.commercial)&&g.commercial[a]},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["noskim"],custom:function(c){var f=b.canonicalizeHostname(c),h="",m=!1;try{h=c.protocol,f.charAt(0)}catch(k){return!0}m=Boolean(""===f||
!h.match(/^https?:$/i)||g.norewrite[f]);if(h=!m)var h=b.cache(c,"type"),q=b.cache(c,"params")||{},h=!Boolean(h||q.type);h&&(m=Boolean(a===f||!g.rewrite_original||!g.rewrite_any&&!d.isCommercial(c)));return m}});return function(a){return this.allowed(a)&&c(a,{ancestors:!1})}}(),log:function(a,c,e,f){var d,m=b.toQuery({libId:g.library_id,nocache:b.uniqid()});d="pixel.gif";if("custom"===a)m+="&"+b.toQuery({key:c,type:e}),b.each("array"===b.type(f)?f:[f],function(a){b.each(["e","i","o"],function(c){delete a[c]});
m+="&"+b.toQuery(a)});else{m+="&"+b.toQuery({key:g.key,drKey:g.key?null:g.dr_key,subId:g.sub_id});if("time"===a)d="time.gif",a={time:e,type:c};else if("exception"===a)a={e:c,o:e};else if("info"===a)a={i:c};else return;m+="&"+b.toQuery(a)}d=g.api_url+"/"+d+"?"+m;b.pii.transmits(d)||(b.createEl("img").src=d)},logException:function(a){if(g.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,
b.toQuery(c))}},logTime:function(){var a;return function(c){0===arguments.length?a=(new Date).getTime():this.log("time",c,(new Date).getTime()-a)}}(),onApiClick:function(a,c,e,f,d){var m=f||b.getActualHref(a),k=b.bind(function(){this.redirect(m,b.context(a),c,e)},this);"object"===typeof d&&(d.tracking||d.image)?(f=b.createEl(d.tracking?"iframe":"img",{src:d.tracking||d.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(f),setTimeout(b.entryPoint(k),d.timeout||g.hop_timeout)):
k()},onApiPing:function(a,c,e,f,h,m){g.rewrite_original=!1;h=b.reformatKeys(h||{});var k,l;f=function(a){var c={},e=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,e);return c};l=b.extend(g.plugins,h.plugins);g=b.extend(g,h);delete g.plugins;g.click_timeout=c;g.library_id=a;g.time_ping&&this.logTime("png");"array"===b.type(g.testing_js)&&0<g.testing_js.length&&b.each(g.testing_js,function(a){b.jsonp(a)});b.extend(g.nofollow,f(m));b.extend(g.norewrite,f(e));for(k in g)"on"===k.toLowerCase().substr(0,
2)&&(2<k.length&&"function"===b.type(g[k]))&&(b.on(d,k.toLowerCase().substr(2),b.bind(g[k],window)),delete g[k]);this.initPlugins(l);this.initContext(window);this.fire("libready")},onClick:function(a,c){c=c||window.event;var e=c.ctrlKey||c.metaKey||c.altKey||c.shiftKey,d=c.which&&1===c.which||0===c.button,h=b.eventLink(c);if(h&&d&&!e&&!b.isDefaultPrevented(c)&&this.isRewritable(h)&&this.shouldHandleClick(a,h))return this.click(h),b.preventDefault(c)},onContextmenu:function(a,c){var e=b.eventLink(c||
window.event);e&&(this.isRewritable(e)&&this.shouldHandleClick(a,e))&&this.handleRightClick(e,"setup")},onCopy:function(a){var c,e,f,h=[];if(window.getSelection){e=window.getSelection();a=0;for(c=e.rangeCount;a<c;a++){try{f=e.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(g){}0<f.length&&128>=f.length&&h.push(f)}}b.each(h,function(a){d.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,c){void 0!==c&&void 0!==this.publicOptions()[a]&&
(g[a]=c);return g[a]},ping:function(){var a=!1;return function(){if(!a&&(g.key||g.dr_key)){var c={ref:document.referrer||null};a=!0;b.pii.transmits(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.detectFiltering(b.bind(function(a){a&&(g.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),platform:function(){return b.platforms.findById(g.platform)||b.platforms.NONE},processLink:function(a){var c=b.cache(a,"processors")||{},e=
this.isRewritable(a);b.each(this.registerProcessor(),function(b){!c[b.id]&&(e||b.opts.any)&&b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a},processLinks:function(a){b.each(a,b.bind(this.processLink,this))},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,e,d){c=c||window.top;!b.traits.crossWindowCommunication&&!e?(d=c.open(a,d),d.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.entryPoint(function(){!e||
e===c?c.location=a:b.contextIsAncestor(c,e)?e.location=a:e.location.replace(a)}),0):("_blank"===d&&(d=b.uniqid("win_")),d=b.createA(a,d),d.rel="norewrite",c.document.body.appendChild(d),d.click(),d.parentNode.removeChild(d))},runPlugin:function(a,c){var e=window.document,d=l[a];if(d&&d.initDocuments){if(c)d.initNodes(c);else if(d.init(),"function"===b.type(d.initDocuments)&&"document"===b.type(e)&&d.initDocuments([e]),"function"===b.type(d.initNodes)&&"element"===b.type(e.body))b.on("DOMReady",function(){d.initNodes([e.body])});
d._ran=!0}},registerProcessor:function(){var a=!1,c=[],e=function(e,d){if(void 0===e)return c;"function"===b.type(e)&&(d=b.extend({any:!1},d),c.push({fn:e,id:b.uniqid(),opts:d}),a&&this.initLinks())};e(function(){a=!0});return e}(),shouldHandleClick:function(a,c){var e=!0;a===this.EVENT_LEVEL_LINK&&(e=this.harmony(b.harmony.LINK_EVENTS)||this.isCommercial(c)&&this.harmony(b.harmony.COMMERCIAL_LINK_EVENTS));return e}};d.init();try{delete window.vglnk_self}catch(r){}})("undefined"===typeof vglnk_self?
"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(p,d,b){var u={},g,l;p=d.extend({any:!0,convert_minimum_bid:!1},p);l={getDomains:function(){var g=[];d.each(u,function(b,d){2!==u[d]&&(g.push(d),u[d]=2)});0<g.length&&b.api("domains",{domains:g.join("|"),v:"2"},{fn:d.bind(l.onDomainApi,l)})},init:function(){b.opt("link_target",p.link_target);b.opt("rewrite_any",p.any);b.opt("rewrite_original",!0);(g=!p.any||b.harmony(d.harmony.COMMERCIAL_LINK_EVENTS)||p.convert_minimum_bid)&&b.registerProcessor(d.bind(function(b){this.initDomainLookup();
this.saveDomain(b)},this),{any:!0})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,d.on("DOMReady",d.bind(this.getDomains,this)))}}(),onDomainApi:function(g){var l;"object"===d.type(g)&&"array"===d.type(g.results)?(l=b.opt("commercial")||{},d.each(g.results,function(b){l[b]=!0}),b.opt("commercial",l)):"object"===d.type(g)&&"object"===d.type(g.results)&&(l=b.opt("commercial")||{},d.each(g.results,function(b,a){l[a]=b.unlink?!1:!0}),b.opt("commercial",l),b.registerProcessor(d.bind(function(b){this.minimumBidUnlink(b)},
this),{any:!0}))},saveDomain:function(b){b=d.canonicalizeHostname(b);u[b]=u[b]||1},minimumBidUnlink:function(g){var l=d.canonicalizeHostname(g);!1===(b.opt("commercial")||{})[l]&&d.unlink(g)}};return{init:d.bind(l.init,l),initNodes:function(){g&&l.getDomains()}}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(p,d,b){var u=[],g=b.platform();p={crawl:function(b){if(g&&!("array"!==d.type(b)||0===b.length))b=d.all(b,function(b){return!d.contains(u,b)}),b=this.findPostsById(b),d.each(b,d.bind(function(b){b.content=this.redact(b.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete b.el},this)),b=d.all(b,function(b){return Boolean(b.content&&b.id)}),0<b.length&&this.processPosts(b)},findPostsById:function(b){return d.all(d.map(g.getPosts(),function(b){return{el:b,id:g.getPostId(b)}}),
function(g){return d.contains(b,g.id)})},processPosts:function(l){l=d.map(l,function(b){u.push(b.id);return{c:b.content,i:b.id}});b.api("content",{content:d.toJSON({ct:l,pt:g.id,u:location.href})},{jsonp:!1,ssl:b.opt("dev")?!1:!0})},redact:function(b){return d.pii.redact(b)}};return{"public":{crawl:d.bind(p.crawl,p)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(p,d,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(p,d,b){p=d.extend({key:null},p);var u={init:function(b){d.each(this.getDRSearchForms(b),function(b){if(!d.cache(b,"evented")){var g=u.getInput(b),n=function(){g.value||d.css(g,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};d.cache(b,"evented",!0);b.onsubmit=null;g.onfocus=null;g.onblur=null;d.on(g,"focus",function(){d.css(g,{"background-image":"none"})});d.on(g,"blur",n);n();d.on(b,"submit",function(d){u.onSubmit(d,b)})}})},
getDRSearchForms:function(b){var l=[];d.each(b,function(b){"element"===d.type(b)&&d.each(b.getElementsByTagName("form"),function(b){u.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&l.push(b)})});return l},getInput:function(b){return b.p||b.q2},onSubmit:function(g,l){g=g||window.event;var m="http://shop.ebay.com/i.html?"+d.toQuery({_nkw:u.getInput(l).value}),m=d.createA(m,"_blank");d.cache(m,"params",{key:p.key});b.click(m);return d.preventDefault(g)}};if(p.key)return{init:d.bind(u.init,u),
initNodes:function(b){u.init(b)}}};window.vglnk=window.vglnk||{};window.vglnk.harmony_plugin=function(p,d,b){p=d.extend({level:d.harmony.DEFAULT},p);return{init:function(){var d=parseFloat(p.level,10);isFinite(d)&&b.opt("harmony_level",d)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(p,d,b,u){var g,l={uuid:"uuid",index:"idx",optimized_url:"url",aliases:"aka"};g={cache:function(){var b={},d={};return{links:{get:function(d){return b[d]},set:function(d,a){var c={};c[l.optimized_url]=a[l.optimized_url];c[l.uuid]=a[l.uuid];c[l.aliases]=a[l.aliases];b[d]=c}},stats:{increment:function(b,a){d[b]||(d[b]={});if(a)if("rep"===a)d[b].rep=(d[b].rep||0)+1;else{var c;c=d[b].ex=d[b].ex||{};c[a]=(c[a]||0)+1}else d[b].n=(d[b][l.insertion_count]||0)+1},getAndReset:function(){var b=
d;d={};return b}}}}(),filterLinkNodes:function(){var b={sameDomainOrInternal:function(){var b=window.location.hostname;return function(a){return b===a.hostname}}()},n=function(g){return d.all(g,function(a){return d.reduce(!0,b,function(c,b){return c&&!b(a)})})};return function(b){var a={needs_optimization:[],needs_call:[]};d.each(n(b),function(c){var b=g.cache.links.get(c.href);b&&b[l.uuid]&&d.cache(c,"uuid",b[l.uuid]);b&&b[l.optimized_url]?a.needs_optimization.push(c):b&&"false"===b[l.optimized_url]||
a.needs_call.push(c)});return a}}(),generateAliases:function(b){var n=g.cache.links.get(b.href),p=[],p=p.concat(n[l.aliases]||[]);p.push(d.canonicalizeHostname(b.href));p.push(d.canonicalizeHostname(n[l.optimized_url]));return d.unique(p)},getLinks:function(){var m=function(b){var g=[];d.each(b,function(a){g.push(a.href)});return g};return function(l){var p=d.unique(m(l));b.api("optimize",{links:p,u:location.href,ver:2},{fn:d.bind(g.onOptimizeApi,g)},p,l)}}(),log:d.batchable(function(){var b={stats:d.toJSON(g.cache.stats.getAndReset())};
4<b.stats.length&&u("loJsLog",b)},function(){return{timeout:1E3}}),onOptimizeApi:function(b,n,p){"object"===d.type(b)&&(d.each(["opt","non","unk"],function(a){b[a]&&b[a].length&&d.each(b[a],function(c){var b=n[c[l.index]];"non"===a&&(c[l.optimized_url]=!1);g.cache.links.set(b,c)})}),p=g.filterLinkNodes(p),g.optimizeLinks(p.needs_optimization))},optimizeLinks:function(b){d.each(b,function(b){d.cache(b,"rewrit",!1)});b=g.runExclusionFilters(b);d.each(b,this.optimizeLink);d.traits.json&&g.log()},optimizeLink:function(){var b=
function(a){return a.replace(/^https?:\/\//,"")},n=function(a,c){for(var b;b=a.firstChild;)a.removeChild(b);a.appendChild(document.createTextNode(c))},r=function(a){var c=a.href,e=a.textContent||a.innerText,f=Boolean(e),h=g.generateAliases(a),l=function(){var a=b(c).toLowerCase(),f=e.toLowerCase().replace(a,"");return d.reduce(!1,h,function(a,c){return a||-1!==f.indexOf(c.toLowerCase())})},k=function(){var a=e.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+d.map(a,d.escapeRegExp).join(".+")+
"$").test(c)},q=function(){var c=d.canonicalizeHostname(a);return d.canonicalizeHostname(d.createEl("a",{href:e}))===c},n=function(){var c;return q()?(c=d.fromQuery(a.search),d.find(c,function(a){return a===e})):!1};return{full_replace:Boolean(f&&(c===e||b(c)===e||k()||n())),exclude:Boolean(f&&l()),partial_replace:Boolean(f&&(-1!==e.indexOf(c)||-1!==e.indexOf(b(c))))}};return function(a){var c,e=g.cache.links.get(a.href),f=e[l.optimized_url];c=r(a);if(f&&!p.observer){if(c.full_replace)n(a,f),g.cache.stats.increment(e[l.uuid],
"rep");else{if(c.exclude){g.cache.stats.increment(e[l.uuid],"a");return}c.partial_replace&&(c="undefined"!==d.type(a.textContent)?a.textContent:a.innerText,c=-1!==c.indexOf(a.href)?c.replace(a.href,f):c.replace(b(a.href),f),n(a,c),g.cache.stats.increment(e[l.uuid],"rep"))}f=-1===f.indexOf("http://")?"http://"+f:f;a.href=f}g.cache.stats.increment(e[l.uuid]);d.cache(a,"rewrit",!0)}}(),runExclusionFilters:function(){var b=d.generateNodeFilter({classes:["nooptimize","norewrite"],rels:["nooptimize","norewrite",
"noskim"],custom:function(b,a){if(a)return Boolean(d.cache(b,"type"))}}),n=function(){var b=function(a,b){var f=d.reduce([],["prev_tokens","next_tokens"],function(b,e){a[e]&&a[e].length&&(b=b.concat(a[e]));return b}).join(" ").toLowerCase();return d.reduce(!1,b,function(a,b){return a||-1!==f.indexOf(b.toLowerCase())})},a=function(){var a=function(a){a="undefined"!==d.type(a.textContent)?a.textContent:a.innerText;return d.all(a.split(/\s+/g),function(a){return""!==a})};return function(b){for(var f=
{prev_tokens:[],next_tokens:[]};b&&b!==document.body.parentNode;){for(var g=f,l=b.previousSibling,k=b.nextSibling;l||k;)l&&(d.nodesOfType([l],1,3).length&&"SCRIPT"!==l.tagName)&&(g.prev_tokens=g.prev_tokens.concat(a(l).reverse())),l=!l?!1:l.previousSibling,k&&(d.nodesOfType([k],1,3).length&&"SCRIPT"!==k.tagName)&&(g.next_tokens=g.next_tokens.concat(a(k))),k=!k?!1:k.nextSibling;if(20<f.prev_tokens.length+f.next_tokens.length+0)break;b=b.parentNode}return f}}();return function(c){var d=g.generateAliases(c);
c=a(c);80<c.prev_tokens.length+c.next_tokens.length+0&&(c.prev_tokens=c.prev_tokens.slice(0,40),c.next_tokens=c.next_tokens.slice(0,40));c.prev_tokens=c.prev_tokens.reverse();return!b(c,d)}}();return function(p){return d.all(p,function(a){var c=g.cache.links.get(a.href)[l.uuid];if(b(a)){if(!n(a))return g.cache.stats.increment(c,"p"),!1}else return g.cache.stats.increment(c,"n"),!1;return!0})}}()};return{initNodes:function(b){var l;b=d.nodesOfType(b,1);b=d.withScope(b,"a[href]",{ancestors:!1,consolidate:!0});
b=g.filterLinkNodes(b);(l=b.needs_optimization)&&l.length&&g.optimizeLinks(l);(b=b.needs_call)&&b.length&&g.getLinks(b)}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(p,d,b,u){var g,l,m,n=null,r=null;p=d.extend({cat:null,key:null,link_phrases:!0,link_target:null,link_urls:!0,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,ui:!0},p);if(p.key)return g=b.platform(),l={cache:function(){var a={},b={},e=function(e,f){var g={};d.isArray(f)&&0<f.length&&d.find(f,function(a){if(b[a]){if(e)return g[e]=b[a][e],!0;d.each(b[a],function(a,b){g[b]||(g[b]=a)})}});g=d.extend(d.clone(a),g);return e?g[e]:g},f=function(e,
f,g){(g=d.isArray(g)&&0<g.length?g:null)&&d.each(g,function(a){b[a]=b[a]||{};"L"!==f.type&&(b[a][e]=f)});if(!g||"L"===f.type)a[e]||(a[e]=f);return!0};return function(a,b,c){var g=d.all(d.toArray(arguments),function(a){return Boolean(a)});"array"===d.type(g[g.length-1])&&(c=g.pop());a=g[0];b=g[1];if(1>=g.length)return e(a,c);if(2===g.length)return f(a,b,c)}}(),focusLink:function(a){a.id||(a.id=d.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var a,
c,e=b.opt("partner"),d={};for(a in e)break;if(a)for(c in e[a])d[a+"_"+c]=e[a][c];return d},getPhrases:function(a,c){b.api("insert",d.extend(l.getPartnerParams(),{cat:p.cat,i:c?c.join("|"):null,mode:p.mode,pt:g.id,ps:p.product_source,u:location.href}),{fn:d.bind(l.onInsertApi,l)},a,c)},hasCalled:function(){var a={},b=function(b){return d.isArray(b)&&b.length?Boolean(d.all(b,function(b){return a[b]}).length===b.length):Boolean(a[d.platforms.DEFAULT_POST_ID])},e=function(b){d.isArray(b)&&b.length?d.each(b,
function(b){a[b]=!0}):a[d.platforms.DEFAULT_POST_ID]=!0};return function(a,d){return d?e(a):b(a)}}(),init:function(){p.scope=p.scope||g.scope;p.link_urls&&(m=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"))},initLink:function(a,c,e){var f=
p.link_target;if(f="U"===c.type?b.opt("link_target"):f||e)a.target=f;a.href||(a.href=c.url);a.rel="nofollow";d.cache(a,"params",{exp:n,key:p.key,mid:c.mid,type:c.type||null});d.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var a,b=d.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return d.matches(a,"a")&&Boolean(a.href)}}),
e=function(a,d,g,h){if(b(d,{ancestors:!Boolean(h),self:!0}))if(3===d.nodeType)f(a,d,g);else if(1===d.nodeType)for(d=d.firstChild;d;)h=d.nextSibling,e(a,d,g,!0),d=h},f=function(a,b,c){var d=!1,e=b.parentNode,f=function(a,b){e.insertBefore(a,b);e.removeChild(b)};e&&(b.data&&(d=a.test(b.data.replace(/\s+/," "))),d&&g(a,b,c,f))},g=function(b,c,e,f){for(var g,h,n,r,u=function(b){var c;b=!b||!p.per_phrase||!a[b.phrase]||a[b.phrase].count<p.per_phrase;c=!p.per_page||d.reduce(0,a,function(a,b){return a+b.count})<
p.per_page;return b&&c},P=function(a,b,c){var e,f,g;if(!c.phrase)return!0;f=d.createEl("span");b.parentNode.insertBefore(f,b);f.appendChild(b);g=d.geometry(f);(p.proximity||p.same_proximity)&&d.find(l.cache(a),function(a){var b,f;if(a.links){if((b=l.normalizePhrase(a.phrase)===l.normalizePhrase(c.phrase))&&!p.same_proximity||!b&&!p.proximity)return!1;f=b?Math.max(p.same_proximity,p.proximity):p.proximity;a.links=d.all(a.links,function(a){var b=d.isInDom(a.el);!e&&b&&(e=d.find(a.segments,function(a){a=
a.geometry;a=d.extend({},a);a.x1-=f;a.y1-=f;a.x2+=f;a.y2+=f;if(a.x1<g.x2&&a.x2>g.x1&&a.y1<g.y2&&a.y2>g.y1)return!0}));return b});return e}});return function(a){f.parentNode.insertBefore(b,f);f.parentNode.removeChild(f);return a}(!e)},U=function(a,b){var c,e,f,g,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(e=k.length;c<e;c++)f=k[c],void 0===g||f.offsetTop===g.offsetTop?l.els.push(f):(h.segments.push(l),l={els:[f]}),g=f;l.geometry=d.geometry.apply(d,l.els);h.segments.push(l);
b.links=b.links||[];b.links.push(h);return b};c&&c.data&&""!==c.data&&(Boolean(n=c.data.match(/^\s+/))||Boolean(n=c.data.match(b)));)h=n[0],r=n.slice(1).join(""),g=(g=l.normalizePhrase(r))?l.cache(g,e):null,h=c.data.indexOf(h)+h.length-r.length,0<h&&(c=c.splitText(h)),h=c.length<=r.length?null:c.splitText(r.length),r&&!g&&(g={url:r.match(/^https?:\/\//i)?r:"http://"+r,type:"U"}),g&&(g.url.match(/https?:\/\//i)&&r&&u(g)&&P(e,c,g))&&(r=m(r,g),d.cache(r,"unlinked")||(f(r,c),U(r,g),c=g.phrase||g.url,
a[c]=a[c]||{count:0,phrase:g.phrase,type:g.type},a[c].count++)),c=h},m=function(a,b){var c;c=d.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";d.cache(c,"type","inserted");d.cache(c,"phrase",a);p.ui&&"U"!==b.type&&(c.title="Link added by VigLink");l.initLink(c,b);return c};return function(f,g){var h=l.regexp(g);a={};h&&(d.each(d.all(f,b),function(a){e(h,a,g)}),p.link_phrases&&l.log(a))}}(),loadPhrases:function(a,b,e){d.each(a,function(a){a.phrase&&
a.url&&(a.phrase=l.normalizePhrase(a.phrase),l.cache(a.phrase,{count:0,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},e))});l.hasCalled(e,!0);this.insertLinks(b,e)},log:function(a){var b=0,e=0,f=[];d.each(a,function(a,d){var g=parseInt(a.count,10);0<g&&("U"===a.type?e+=g:f.push({phrase:d,type:a.type,count:g}),b+=g)});0<b&&u("insert",[{ct:b,cl:e,exp:n,imp_id:r,phrases:d.toJSON(f)}])},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},onInsertApi:function(a,
b,e){"object"===d.type(a)&&(n=a.exp,r=a.imp_id,a.results&&this.loadPhrases(a.results,b,e))},regexp:function(a){var b;a=l.cache(a);a=d.map(a,function(a,b){return d.escapeRegExp(b).split(" ").join("\\s+")});0<a.length&&(b="(?:^|[\\s\"'\\(])("+a.join("|")+")(?=\\s|\\W*$|\\W{2})",b=RegExp(m?"(?:"+b+"|"+m.source+")":b,"i"));return b||m}},{init:d.bind(l.init,l),initNodes:function(a){var b;p.scope&&(a=d.unique(d.reduce([],d.withScope(a,p.scope),function(a,b){return a.concat(b[1])})));a.length&&(b=g.getPostIds(a),
p.link_phrases&&!l.hasCalled(b)?l.getPhrases(a,b):l.insertLinks(a,b))}}};
